package Mapeos;
// Generated 08/02/2019 09:56:35 by Hibernate Tools 4.3.1



/**
 * AspirantesHasCompetenciasId generated by hbm2java
 */
public class AspirantesHasCompetenciasId  implements java.io.Serializable {


     private int aspirantesDni;
     private String aspirantesEscuelaNombreEscuela;
     private int competenciasIdCompetencias;
     private String competenciasCategoriasNombreCategoria;
     private String competenciasDisciplinasDisciplina;
     private int competenciasTorneosIdTorneos;
     private int competenciasTorneosSedesIdSedes;

    public AspirantesHasCompetenciasId() {
    }

    public AspirantesHasCompetenciasId(int aspirantesDni, String aspirantesEscuelaNombreEscuela, int competenciasIdCompetencias, String competenciasCategoriasNombreCategoria, String competenciasDisciplinasDisciplina, int competenciasTorneosIdTorneos, int competenciasTorneosSedesIdSedes) {
       this.aspirantesDni = aspirantesDni;
       this.aspirantesEscuelaNombreEscuela = aspirantesEscuelaNombreEscuela;
       this.competenciasIdCompetencias = competenciasIdCompetencias;
       this.competenciasCategoriasNombreCategoria = competenciasCategoriasNombreCategoria;
       this.competenciasDisciplinasDisciplina = competenciasDisciplinasDisciplina;
       this.competenciasTorneosIdTorneos = competenciasTorneosIdTorneos;
       this.competenciasTorneosSedesIdSedes = competenciasTorneosSedesIdSedes;
    }
   
    public int getAspirantesDni() {
        return this.aspirantesDni;
    }
    
    public void setAspirantesDni(int aspirantesDni) {
        this.aspirantesDni = aspirantesDni;
    }
    public String getAspirantesEscuelaNombreEscuela() {
        return this.aspirantesEscuelaNombreEscuela;
    }
    
    public void setAspirantesEscuelaNombreEscuela(String aspirantesEscuelaNombreEscuela) {
        this.aspirantesEscuelaNombreEscuela = aspirantesEscuelaNombreEscuela;
    }
    public int getCompetenciasIdCompetencias() {
        return this.competenciasIdCompetencias;
    }
    
    public void setCompetenciasIdCompetencias(int competenciasIdCompetencias) {
        this.competenciasIdCompetencias = competenciasIdCompetencias;
    }
    public String getCompetenciasCategoriasNombreCategoria() {
        return this.competenciasCategoriasNombreCategoria;
    }
    
    public void setCompetenciasCategoriasNombreCategoria(String competenciasCategoriasNombreCategoria) {
        this.competenciasCategoriasNombreCategoria = competenciasCategoriasNombreCategoria;
    }
    public String getCompetenciasDisciplinasDisciplina() {
        return this.competenciasDisciplinasDisciplina;
    }
    
    public void setCompetenciasDisciplinasDisciplina(String competenciasDisciplinasDisciplina) {
        this.competenciasDisciplinasDisciplina = competenciasDisciplinasDisciplina;
    }
    public int getCompetenciasTorneosIdTorneos() {
        return this.competenciasTorneosIdTorneos;
    }
    
    public void setCompetenciasTorneosIdTorneos(int competenciasTorneosIdTorneos) {
        this.competenciasTorneosIdTorneos = competenciasTorneosIdTorneos;
    }
    public int getCompetenciasTorneosSedesIdSedes() {
        return this.competenciasTorneosSedesIdSedes;
    }
    
    public void setCompetenciasTorneosSedesIdSedes(int competenciasTorneosSedesIdSedes) {
        this.competenciasTorneosSedesIdSedes = competenciasTorneosSedesIdSedes;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AspirantesHasCompetenciasId) ) return false;
		 AspirantesHasCompetenciasId castOther = ( AspirantesHasCompetenciasId ) other; 
         
		 return (this.getAspirantesDni()==castOther.getAspirantesDni())
 && ( (this.getAspirantesEscuelaNombreEscuela()==castOther.getAspirantesEscuelaNombreEscuela()) || ( this.getAspirantesEscuelaNombreEscuela()!=null && castOther.getAspirantesEscuelaNombreEscuela()!=null && this.getAspirantesEscuelaNombreEscuela().equals(castOther.getAspirantesEscuelaNombreEscuela()) ) )
 && (this.getCompetenciasIdCompetencias()==castOther.getCompetenciasIdCompetencias())
 && ( (this.getCompetenciasCategoriasNombreCategoria()==castOther.getCompetenciasCategoriasNombreCategoria()) || ( this.getCompetenciasCategoriasNombreCategoria()!=null && castOther.getCompetenciasCategoriasNombreCategoria()!=null && this.getCompetenciasCategoriasNombreCategoria().equals(castOther.getCompetenciasCategoriasNombreCategoria()) ) )
 && ( (this.getCompetenciasDisciplinasDisciplina()==castOther.getCompetenciasDisciplinasDisciplina()) || ( this.getCompetenciasDisciplinasDisciplina()!=null && castOther.getCompetenciasDisciplinasDisciplina()!=null && this.getCompetenciasDisciplinasDisciplina().equals(castOther.getCompetenciasDisciplinasDisciplina()) ) )
 && (this.getCompetenciasTorneosIdTorneos()==castOther.getCompetenciasTorneosIdTorneos())
 && (this.getCompetenciasTorneosSedesIdSedes()==castOther.getCompetenciasTorneosSedesIdSedes());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAspirantesDni();
         result = 37 * result + ( getAspirantesEscuelaNombreEscuela() == null ? 0 : this.getAspirantesEscuelaNombreEscuela().hashCode() );
         result = 37 * result + this.getCompetenciasIdCompetencias();
         result = 37 * result + ( getCompetenciasCategoriasNombreCategoria() == null ? 0 : this.getCompetenciasCategoriasNombreCategoria().hashCode() );
         result = 37 * result + ( getCompetenciasDisciplinasDisciplina() == null ? 0 : this.getCompetenciasDisciplinasDisciplina().hashCode() );
         result = 37 * result + this.getCompetenciasTorneosIdTorneos();
         result = 37 * result + this.getCompetenciasTorneosSedesIdSedes();
         return result;
   }   


}


