package Mapeos;
// Generated 08/02/2019 09:56:35 by Hibernate Tools 4.3.1



/**
 * AspirantesHasCompetencias generated by hbm2java
 */
public class AspirantesHasCompetencias  implements java.io.Serializable {


     private AspirantesHasCompetenciasId id;
     private String compitio;
     private Integer resultado;

    public AspirantesHasCompetencias() {
    }

	
    public AspirantesHasCompetencias(AspirantesHasCompetenciasId id) {
        this.id = id;
    }
    public AspirantesHasCompetencias(AspirantesHasCompetenciasId id, String compitio, Integer resultado) {
       this.id = id;
       this.compitio = compitio;
       this.resultado = resultado;
    }
   
    public AspirantesHasCompetenciasId getId() {
        return this.id;
    }
    
    public void setId(AspirantesHasCompetenciasId id) {
        this.id = id;
    }
    public String getCompitio() {
        return this.compitio;
    }
    
    public void setCompitio(String compitio) {
        this.compitio = compitio;
    }
    public Integer getResultado() {
        return this.resultado;
    }
    
    public void setResultado(Integer resultado) {
        this.resultado = resultado;
    }




}


