package Mapeos;
// Generated 08/02/2019 09:56:35 by Hibernate Tools 4.3.1



/**
 * CompetenciasId generated by hbm2java
 */
public class CompetenciasId  implements java.io.Serializable {


     private int idCompetencias;
     private String categoriasNombreCategoria;
     private String disciplinasDisciplina;
     private int torneosIdTorneos;
     private int torneosSedesIdSedes;

    public CompetenciasId() {
    }

    public CompetenciasId(int idCompetencias, String categoriasNombreCategoria, String disciplinasDisciplina, int torneosIdTorneos, int torneosSedesIdSedes) {
       this.idCompetencias = idCompetencias;
       this.categoriasNombreCategoria = categoriasNombreCategoria;
       this.disciplinasDisciplina = disciplinasDisciplina;
       this.torneosIdTorneos = torneosIdTorneos;
       this.torneosSedesIdSedes = torneosSedesIdSedes;
    }
   
    public int getIdCompetencias() {
        return this.idCompetencias;
    }
    
    public void setIdCompetencias(int idCompetencias) {
        this.idCompetencias = idCompetencias;
    }
    public String getCategoriasNombreCategoria() {
        return this.categoriasNombreCategoria;
    }
    
    public void setCategoriasNombreCategoria(String categoriasNombreCategoria) {
        this.categoriasNombreCategoria = categoriasNombreCategoria;
    }
    public String getDisciplinasDisciplina() {
        return this.disciplinasDisciplina;
    }
    
    public void setDisciplinasDisciplina(String disciplinasDisciplina) {
        this.disciplinasDisciplina = disciplinasDisciplina;
    }
    public int getTorneosIdTorneos() {
        return this.torneosIdTorneos;
    }
    
    public void setTorneosIdTorneos(int torneosIdTorneos) {
        this.torneosIdTorneos = torneosIdTorneos;
    }
    public int getTorneosSedesIdSedes() {
        return this.torneosSedesIdSedes;
    }
    
    public void setTorneosSedesIdSedes(int torneosSedesIdSedes) {
        this.torneosSedesIdSedes = torneosSedesIdSedes;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CompetenciasId) ) return false;
		 CompetenciasId castOther = ( CompetenciasId ) other; 
         
		 return (this.getIdCompetencias()==castOther.getIdCompetencias())
 && ( (this.getCategoriasNombreCategoria()==castOther.getCategoriasNombreCategoria()) || ( this.getCategoriasNombreCategoria()!=null && castOther.getCategoriasNombreCategoria()!=null && this.getCategoriasNombreCategoria().equals(castOther.getCategoriasNombreCategoria()) ) )
 && ( (this.getDisciplinasDisciplina()==castOther.getDisciplinasDisciplina()) || ( this.getDisciplinasDisciplina()!=null && castOther.getDisciplinasDisciplina()!=null && this.getDisciplinasDisciplina().equals(castOther.getDisciplinasDisciplina()) ) )
 && (this.getTorneosIdTorneos()==castOther.getTorneosIdTorneos())
 && (this.getTorneosSedesIdSedes()==castOther.getTorneosSedesIdSedes());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCompetencias();
         result = 37 * result + ( getCategoriasNombreCategoria() == null ? 0 : this.getCategoriasNombreCategoria().hashCode() );
         result = 37 * result + ( getDisciplinasDisciplina() == null ? 0 : this.getDisciplinasDisciplina().hashCode() );
         result = 37 * result + this.getTorneosIdTorneos();
         result = 37 * result + this.getTorneosSedesIdSedes();
         return result;
   }   


}


