package Mapeos;
// Generated 08/02/2019 09:56:35 by Hibernate Tools 4.3.1



/**
 * Competencias generated by hbm2java
 */
public class Competencias  implements java.io.Serializable {


     private CompetenciasId id;

    public Competencias() {
    }

    public Competencias(CompetenciasId id) {
       this.id = id;
    }
   
    public CompetenciasId getId() {
        return this.id;
    }
    
    public void setId(CompetenciasId id) {
        this.id = id;
    }




}


