package Mapeos;
// Generated 08/02/2019 09:56:35 by Hibernate Tools 4.3.1



/**
 * Disciplinas generated by hbm2java
 */
public class Disciplinas  implements java.io.Serializable {


     private String disciplina;

    public Disciplinas() {
    }

    public Disciplinas(String disciplina) {
       this.disciplina = disciplina;
    }
   
    public String getDisciplina() {
        return this.disciplina;
    }
    
    public void setDisciplina(String disciplina) {
        this.disciplina = disciplina;
    }




}


