package Mapeos;
// Generated 08/02/2019 09:56:35 by Hibernate Tools 4.3.1



/**
 * Escuela generated by hbm2java
 */
public class Escuela  implements java.io.Serializable {


     private String nombreEscuela;
     private String direccion;
     private String telefono;

    public Escuela() {
    }

	
    public Escuela(String nombreEscuela) {
        this.nombreEscuela = nombreEscuela;
    }
    public Escuela(String nombreEscuela, String direccion, String telefono) {
       this.nombreEscuela = nombreEscuela;
       this.direccion = direccion;
       this.telefono = telefono;
    }
   
    public String getNombreEscuela() {
        return this.nombreEscuela;
    }
    
    public void setNombreEscuela(String nombreEscuela) {
        this.nombreEscuela = nombreEscuela;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


