package Mapeos;
// Generated 08/02/2019 09:56:35 by Hibernate Tools 4.3.1



/**
 * Sedes generated by hbm2java
 */
public class Sedes  implements java.io.Serializable {


     private Integer idSedes;
     private String nombre;
     private String direccion;
     private String telefono;

    public Sedes() {
    }

    public Sedes(String nombre, String direccion, String telefono) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
    }
   
    public Integer getIdSedes() {
        return this.idSedes;
    }
    
    public void setIdSedes(Integer idSedes) {
        this.idSedes = idSedes;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


